name: Generate profile summary cards

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "23 3 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          USERNAME: EaEa0001
          BRANCH_NAME: main
          THEME: chartreuse_dark
          UTC_OFFSET: 8
